name: Run Pytests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: pytest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest; fi
          pip install -e .

      - name: Configure environment
        run: |
          # Use repo secret if present, else a safe dummy to satisfy settings validation
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY=test-key" >> $GITHUB_ENV
          else
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          fi
          echo "OPENAI_MODEL=gpt-4" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest -q
